/*
 * Business Process Definition: Storno (vacation_storno_wf)
 *
 * Auto-generated by ACS Workflow Export, version 4.3
 *
 * Context: default
 */


/*
 * Cases table
 */
create table vacation_storno_wf_cases (
  case_id               integer primary key
                        references wf_cases on delete cascade
);

/* 
 * Declare the object type
 */


create function inline_0 () returns integer as '
begin
    PERFORM workflow__create_workflow (
        ''vacation_storno_wf'', 
        ''Storno'', 
        ''Storno'', 
        ''Storno Worklfow'', 
        ''vacation_storno_wf_cases'',
        ''case_id''
    );

    return null;

end;' language 'plpgsql';

select inline_0 ();
drop function inline_0 ();

        


/*****
 * Places
 *****/


    select workflow__add_place(
        'vacation_storno_wf',
        'approved', 
        'Approved', 
        1
    );

        

    select workflow__add_place(
        'vacation_storno_wf',
        'rejected', 
        'Rejected', 
        2
    );

        

    select workflow__add_place(
        'vacation_storno_wf',
        'start', 
        'Ready to Approve Storno Request', 
        null
    );

        

    select workflow__add_place(
        'vacation_storno_wf',
        'end', 
        'Process finished', 
        null
    );

        

    select workflow__add_place(
        'vacation_storno_wf',
        'comment_provided', 
        'Comment provided', 
        null
    );

        
/*****
 * Roles
 *****/



	select workflow__add_role (
         'vacation_storno_wf',
         'approve_storno_request',
         'Approve Storno Request',
         1
    );

        

	select workflow__add_role (
         'vacation_storno_wf',
         'provide_',
         'Provide ',
         2
    );

        

/*****
 * Transitions
 *****/



	select workflow__add_transition (
         'vacation_storno_wf',
         'approve_storno_request',
         'Approve Storno Request',
         'approve_storno_request',
         1,
         'user'
	);
	
        

	select workflow__add_transition (
         'vacation_storno_wf',
         'approved',
         'Approved',
         'approve_storno_request',
         2,
         'automatic'
	);
	
        

	select workflow__add_transition (
         'vacation_storno_wf',
         'rejected',
         'Rejected',
         'approve_storno_request',
         3,
         'automatic'
	);
	
        

	select workflow__add_transition (
         'vacation_storno_wf',
         'provide_comment',
         'Provide Comment',
         'provide_',
         4,
         'user'
	);
	
        

/*****
 * Arcs
 *****/



	select workflow__add_arc (
         'vacation_storno_wf',
         'approved',
         'end',
         'out',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'vacation_storno_wf',
         'approved',
         'approved',
         'in',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'vacation_storno_wf',
         'approve_storno_request',
         'comment_provided',
         'in',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'vacation_storno_wf',
         'approve_storno_request',
         'approved',
         'out',
         'wf_callback__guard_attribute_true',
         'approve_storno_p',
         'Approved'
	);

        

	select workflow__add_arc (
         'vacation_storno_wf',
         'approve_storno_request',
         'rejected',
         'out',
         '#',
         '',
         'Rejected'
	);

        

	select workflow__add_arc (
         'vacation_storno_wf',
         'provide_comment',
         'start',
         'in',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'vacation_storno_wf',
         'provide_comment',
         'comment_provided',
         'out',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'vacation_storno_wf',
         'rejected',
         'rejected',
         'in',
         '',
         '',
         ''
	);

        

	select workflow__add_arc (
         'vacation_storno_wf',
         'rejected',
         'end',
         'out',
         '',
         '',
         ''
	);

        

/*****
 * Attributes
 *****/



    select workflow__create_attribute(
        'vacation_storno_wf',
        'approve_storno_p',
        'boolean',
        'Approve the Storno of the Absence?',
	null,
	null,
	null,
        'f',
	1,
	1,
	null,
	'generic'
    );

        

	select workflow__add_trans_attribute_map(
        	'vacation_storno_wf', 
        	'approve_storno_request',
        	'approve_storno_p',
        	1
    );

        

    select workflow__create_attribute(
        'vacation_storno_wf',
        'Comment',
        'richtext',
        'Comment',
	null,
	null,
	null,
        '',
	1,
	1,
	null,
	'generic'
    );

        

    select workflow__create_attribute(
        'vacation_storno_wf',
        'storno_reason',
        'text',
        'Reason for cancellation',
	null,
	null,
	null,
        '',
	1,
	1,
	null,
	'generic'
    );

        

	select workflow__add_trans_attribute_map(
        	'vacation_storno_wf', 
        	'provide_comment',
        	'storno_reason',
        	2
    );

        
/*****
 * Transition-role-assignment-map
 *****/



/*
 * Context/Transition info
 * (for context = default)
 */

insert into wf_context_transition_info
(context_key,
 workflow_key,
 transition_key,
 estimated_minutes,
 instructions,
 enable_callback,
 enable_custom_arg,
 fire_callback,
 fire_custom_arg,
 time_callback,
 time_custom_arg,
 deadline_callback,
 deadline_custom_arg,
 deadline_attribute_name,
 hold_timeout_callback,
 hold_timeout_custom_arg,
 notification_callback,
 notification_custom_arg,
 unassigned_callback,
 unassigned_custom_arg)
values
('default',
 'vacation_storno_wf',
 'approved',
 0,
 '',
 '',
 '',
 'im_workflow__set_object_status_id',
 '16002',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '');

insert into wf_context_transition_info
(context_key,
 workflow_key,
 transition_key,
 estimated_minutes,
 instructions,
 enable_callback,
 enable_custom_arg,
 fire_callback,
 fire_custom_arg,
 time_callback,
 time_custom_arg,
 deadline_callback,
 deadline_custom_arg,
 deadline_attribute_name,
 hold_timeout_callback,
 hold_timeout_custom_arg,
 notification_callback,
 notification_custom_arg,
 unassigned_callback,
 unassigned_custom_arg)
values
('default',
 'vacation_storno_wf',
 'approve_storno_request',
 5,
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'im_workflow__assign_to_supervisor',
 '');

insert into wf_context_transition_info
(context_key,
 workflow_key,
 transition_key,
 estimated_minutes,
 instructions,
 enable_callback,
 enable_custom_arg,
 fire_callback,
 fire_custom_arg,
 time_callback,
 time_custom_arg,
 deadline_callback,
 deadline_custom_arg,
 deadline_attribute_name,
 hold_timeout_callback,
 hold_timeout_custom_arg,
 notification_callback,
 notification_custom_arg,
 unassigned_callback,
 unassigned_custom_arg)
values
('default',
 'vacation_storno_wf',
 'provide_comment',
 5,
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'im_workflow__assign_to_owner',
 '');



/*
 * Context/Role info
 * (for context = default)
 */



/*
 * Context Task Panels
 * (for context = default)
 */

insert into wf_context_task_panels 
(context_key,
 workflow_key,
 transition_key,
 sort_order,
 header,
 template_url,
 overrides_action_p,
 overrides_both_panels_p,
 only_display_when_started_p)
values
('default',
 'vacation_storno_wf',
 'approve_storno_request',
 1,
 'Approve Absence',
 '/packages/intranet-timesheet2-workflow/www/absences/absence-panel',
 'f',
 'f',
 'f');


commit;


